push!(ARGS, "../../input_files/dynamic/no_basin_test/switching/switch1.dat")
include("../../Basin.jl")
pop!(ARGS)
push!(ARGS, "../../input_files/dynamic/no_basin_test/switching/switch2.dat")
include("../../Basin.jl")
pop!(ARGS)
push!(ARGS, "../../input_files/dynamic/no_basin_test/switching/switch3.dat")
include("../../Basin.jl")
pop!(ARGS)
push!(ARGS, "../../input_files/dynamic/no_basin_test/switching/switch4.dat")
include("../../Basin.jl")
pop!(ARGS)
push!(ARGS, "../../input_files/dynamic/no_basin_test/switching/switch5.dat")
include("../../Basin.jl")
pop!(ARGS)

